#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"

options=(
  style=round
  width=9.5
  hidpi=on
  active_color=$BORDER_ACTIVE_COLOR
  background_color=$BORDER_BACKGROUND_COLOR
  blacklist="Leader Key,CleanShot,Tuna"
)

borders "${options[@]}"
